# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(null=True, to='blogApp.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
