# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='contente',
            new_name='content',
        ),
    ]
